### ISSUE TITLE
Feat - [선택] 이메일 가입 및 인증 기능

### ISSUE THREAD

**Issue by KAPUIST** [KAPUIST/Today-I-Workout#5]
- [ ]  **이메일 가입 및 인증 기능**
    - 이메일 가입 시 이메일 인증 기능을 포함하는 것이 좋습니다.
        - [[Nodemailer](https://github.com/nodemailer/nodemailer)](https://github.com/nodemailer/nodemailer)와 같은 패키지 사용을 하여 완료해보세요
        - 회원가입

**Comment by Eomhyein** [comment]
5-feat-선택-이메일-가입-및-인증-기능 : 브랜치명
"[Update] - 회원가입, 이메일인증 01" commit
- 완성본 아님 
- 머지 하면 아직 안됨 큰일남 
- 이메일 인증이 되는지 확인이 필요함 
- 코드 수정 해야됨 
- 백업용으로 한번 올림

**Comment by Eomhyein** [comment]
"[[fix] - 회원가입, 이메일인증 02]"

06.02 이메일 인증이 되는지 확인함
